# Generated by Django 3.1.3 on 2020-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.IntegerField(default=0),
        ),
    ]
