# Generated by Django 3.1.3 on 2020-12-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_auto_20201201_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
