# Generated by Django 3.1.3 on 2020-11-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_newsletterrecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
