# Generated by Django 3.1.3 on 2020-12-02 05:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_profile_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
