# Generated by Django 3.1.3 on 2020-12-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_auto_20201202_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
